<?php $builderHelper = $this->helper('MGS\Fbuilder\Helper\Data'); ?>
<?php $testimonials = $this->getCollection() ?>
<div class="content-block testimonial-block">
	<?php if (count($testimonials)>0): ?>
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $items = $perRowDefault = $this->getPerrow(); ?>
		<?php $perRowTablet = $this->getPerrowTablet(); ?>
		<?php $perRowMobile = $this->getPerrowMobile(); ?>
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $slideBy = 1 ?>
			<?php $columnCount = $perRowDefault * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideBy = $this->getSlideBy() ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		
		<?php if($useSlider): ?>
		
		<?php 
			$settingMode = 'multiple'; 
			$navPosition = $this->getNavigationPosition();
	
			$navType = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/navigation');
			if($navType=='image'){
				$nextIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/next_image');
				$prevIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/prev_image');
				$navHtml = '["<span><img src=\''.$builderHelper->getMediaUrl().'mgs/fbuilder/slider/'.$prevIcon.'\'/></span>", "<span><img src=\''.$builderHelper->getMediaUrl().'mgs/fbuilder/slider/'.$nextIcon.'\'/></span>"]';
			}else{
				$nextIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/next_font_class');
				$prevIcon = $builderHelper->getStoreConfig('fbuilder/'.$settingMode.'_slider/prev_font_class');
				$navHtml = '["<span><em class=\''.$prevIcon.'\'></em></span>", "<span><em class=\''.$nextIcon.'\'></em></span>"]';
			}
		?>
		<?php endif ?>
		<div class="block widget mgs-testimonial">
			<div id="testimonial-<?php echo $blockId; ?>" class="items<?php if($useSlider): ?> owl-carousel mgs-owl-carousel mgs-carousel-<?php echo $settingMode ?> nav-type-<?php echo $navType ?> nav-position-<?php echo $navPosition ?> <?php if($this->getHideNav() && ((($items==1) && ($navPosition!='middle-outside')) || (($items>1) && ($navPosition=='middle-inside')))): ?> autohide-nav<?php endif ?> dot-position-<?php echo $this->getPaginationPosition()?><?php else: ?> line row-<?php echo $perRowDefault ?> row-tablet-<?php echo $perRowTablet ?> row-mobile-<?php echo $perRowMobile ?><?php endif ?>">
				<?php $i=0; $j=0; foreach ($testimonials as $_testimonial): $i++; ?>
					
					<?php if($slideMultiRow): ?>
						<?php if ($j++ % $columnCount == 0): ?>
						<div class="line">
						<?php endif ?>
					<?php endif ?>
					
						<div class="testimonial-item<?php if($slideMultiRow || !$this->hasData('number_row')): ?> col<?php endif ?>">
							<div class="testimonial-content">
								<?php if(!$this->getHidePhoto()): ?>
									<div class="author-thumbnail">							
										<img class="img-responsive" src="<?php echo $this->getAvatarUrl($_testimonial->getAvatar()) ?>" alt="">
									</div>
								<?php endif ?>
								<div class="content">
									<blockquote<?php if($this->getContentItalic()):?> class="font-italic"<?php endif ?>><?php echo $_testimonial->getContent() ?></blockquote>
									<?php if(!$this->getHideName() || !$this->getHideInfo()): ?>
										<div class="author-info">
											<?php if(!$this->getHideName()): ?>
												<div class="name"><?php echo $_testimonial->getName() ?></div>
											<?php endif ?>
											<?php if(!$this->getHideInfo() && ($_testimonial->getInformation()!='')): ?>
												<div class="infomation"><?php echo $_testimonial->getInformation() ?></div>
											<?php endif ?>
										</div>
									<?php endif ?>
									
								</div>
							</div>
						</div>
							
					<?php if($slideMultiRow): ?>
						<?php if ($j % $columnCount == 0 || $j == count($testimonials)): ?>
						</div>
						<?php endif ?>
					<?php endif ?>
					
				<?php endforeach; ?>
			</div>
		</div>
		<?php if($useSlider): ?>
			<?php $autoPlay = $this->getAutoplay() ? 'true' : 'false'; ?>
			<?php $stopAuto = $this->getStopAuto() ? 'true' : 'false'; ?>
			<?php $nav = $this->getNavigation() ? 'true' : 'false'; ?>
			<?php $dot = $this->getPagination() ? 'true' : 'false'; ?>
			<?php $rtl = $this->getRtl() ? 'true' : 'false'; ?>
			<?php $loop = $this->getLoop() ? 'true' : 'false'; ?>
			<?php $slideBy = $slideBy ? $slideBy : 1; ?>
			
			<script type="text/javascript">
				require([
					'jquery',
					'owlcarousel'
				], function ($) {
					var owlpost<?php echo $blockId ?> = $('#testimonial-<?php echo $blockId; ?>').owlCarousel({
						<?php if($slideMultiRow): ?>
							items: 1,
						<?php else: ?>
							items: <?php echo $perRowDefault; ?>,
						<?php endif ?>
						autoplay: <?php echo $autoPlay ?>,
						autoplayHoverPause: <?php echo $stopAuto ?>,
						nav: <?php echo $nav ?>,
						dots: <?php echo $dot ?>,
						slideBy: <?php echo $slideBy ?>,
						rtl: <?php echo $rtl; ?>,
						loop: <?php echo $loop; ?>,
						<?php if(!$slideMultiRow):?>margin: <?php echo $this->getSlideMargin() ?>,<?php endif ?>
						<?php if($navPosition=='top-left' || $navPosition=='top-right'): ?>
							onInitialized: function(){
								$("#testimonial-<?php echo $blockId; ?> .owl-nav").attr('style', 'top:<?php echo $this->getNavTop() ?>px');
							},
						<?php endif ?>
						<?php if(!$slideMultiRow): ?>
						responsive:{
							0:{
								items:<?php echo $perRowMobile; ?>,
								nav: false,
							},
							571:{
								items:<?php echo $perRowTablet; ?>
							},
							1200:{
								items:<?php echo $perRowDefault; ?>
							}
						},
						<?php endif ?>
						navText: <?php echo $navHtml ?>,
						autoHeight:true
					});
				});
			</script>
		<?php endif ?>
	<?php else: ?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find testimonial matching the selection.') ?></div></div>
	<?php endif ?>
</div>