<script type="text/javascript">
	require([
		'jquery'
	], function(jQuery){
		(function($) {
			$.fn.mColorPicker.defaults.imageFolder="<?php echo $this->getViewFileUrl('MGS_Fbuilder::images') ?>/";
			
			var arrInput = ['general_container_width', 'general_column_padding', 'social_instagram_access_token', 'social_snapppt_script', 'social_google_api_key', 'font_style_custom_style', 'export_page_id', 'import_page_id', 'import_file'];
			$.each( arrInput, function( i, val ) {
				if($('#fbuilder_'+val).length){
					$('#fbuilder_'+val).attr('disabled', 'disabled');
				}
				if($('#fbuilder_'+val+'_inherit').length){
					$('#fbuilder_'+val+'_inherit').click(function(){
						setTimeout(function(){
							$('#fbuilder_'+val).attr('disabled', 'disabled');
						}, 5);
					});
				}
			});
		})(jQuery);
	});
</script>